version: 2.1

jobs:
  build:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd docs/ 
      - run: bibtex solution-architecture && pdflatex -interaction=nonstopmode -halt-on-error *.tex

workflows:
  latex:
    jobs:
      - build:
          filters:
            branches:
              only: main