version: '2.1'
orbs:
  terraform: 'circleci/terraform@dev:alpha'
workflows:
  test_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      # - terraform/plan:
      #     checkout: true
      #     context: terraform
      #     persist-workspace: true
      #     requires:
      #       - terraform/validate

