version: 2.1

jobs:
  build:
    docker: # executor type
      - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty

      steps:
        # Commands run in the primary container
        - checkout
        - run: sudo apt-get -qq && sudo apt-get install -y --no-install-recommends texlive-full
        - run: pdflatex -interaction=nonstopmode -halt-on-error docs/*.tex

workflows:
  pdflatex:
    jobs:
      - build:
          filters:
            branches:
              only: main
