version: 2.1

jobs:
  build:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      - run: cd docs/ 
      - run: pdflatex solution-architecture interaction=nonstopmode solution-architecture.tex
      - run: bibtex solution-architecture.aux 
      - run: pdflatex -interaction=nonstopmode -halt-on-error solution-architecture.tex

workflows:
  latex:
    jobs:
      - build:
          filters:
            branches:
              only: main